ER図
tohohosan/MuseUP pull request #5
Opened 2024-09-26 06:19 UTC by tohohosan

ER図を作成して README に追記しました。
![空白の図](https://github.com/user-attachments/assets/e892b186-f7e9-41f8-860e-f199dfb987e3)

2024-09-26 06:44 UTC, Tsuchiya2 commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びER図への反映をお願いします。
...

- imagesテーブルは画像を保存するためのテーブルかと推測したのですが、画像データを保存するカラムは無くても大丈夫でしょうか？

2024-09-28 04:57 UTC, rdhdchloe commented
ご対応ありがとうございます！
以下コメントになります。

---

Imagesテーブルですが、
ミュージアムを投稿する際のイメージでしょうか？ミュージアムの口コミを投稿する際のイメージでしょうか？

Listsテーブルですが、多対多の関係性になると思いますが、
中間テーブルを使用した方が良いと思いますがいかがでしょうか。

ご確認よろしくお願いします。

2024-09-28 14:08 UTC, tohohosan commented
ご確認くださいましてありがとうございます！
Imagesテーブルにつきましては、ミュージアムを投稿する際のイメージで想定しております。
また、Listsテーブルにつきましては、ミュージアムとリストは多対多の関係であることを失念しておりました。
ご指摘賜りまして誠にありがとうございます！ミュージアムとリスト間の中間テーブルを作成し、反映いたしました。

お手数ですが改めて以下をご確認いただけますようよろしくお願い申し上げます。
![空白の図 (2)](https://github.com/user-attachments/assets/906d0310-55f4-4284-8a04-bd3266b6e888)

2024-09-29 08:19 UTC, tarakish requested changes
修正確認しました。以下追加のコメントです！

---

- Users
  - 認証にはなにかgemを想定でしょうか？その場合は必要なカラムが足りているかご確認をお願いします！
  - 外部認証系のカラムも見当たりませんでしたのでそちらも合わせてご確認いただければと思います。

- Museums
  - こちらはGoogle Map上に表示するような機能はありますか？その場合はaddressから表示できるのか確認済みでしょうか？（緯度経度情報が必要になるかと思い確認です！）

- Reviews
  - 細かい点ですが、reviewカラムはテーブル名と意味が被っているので`内容`を表すようなcontent, descriptionなどの方が良さそうです。（データの取得時に`@review.review`だと少し分かりにくいかと思いました）

- Note
  - noteカラムの上記と同様です！

2024-10-01 06:08 UTC, tohohosan commented
ご指摘いただきまして誠にありがとうございます。
使用する Gem や API を考慮して再度修正いたしました。
修正した点を以下におまとめしますので、お手数ですがご確認くださいますと幸いです。

**User テーブル**
・ユーザーのプロフィール画像を登録できることを想定していたため、失念していた image カラムを追加しております。
・gem は Devise を使用する想定です。パスワードリセットのためのカラムを追加しました。
・OmniAuth を使用して Google や Twitter アカウントでログインするためのカラムを追加しました。

**Museum テーブル**
・Geocoding APIを使って、ユーザーが登録した住所（address カラム）を緯度と経度に変換し、Google Map APIで博物館の位置を表示できるように、緯度経度のカラムを追加しました。

**Review/Note テーブル**
・テーブル名と重複しているカラム名を修正しました。

![空白の図 (3)](https://github.com/user-attachments/assets/0ecefe87-29fd-4f6e-b894-a7ebce962bd4)

2024-10-01 09:57 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。
修正が必要になった際は適宜修正して開発を進めましょう。

2024-10-01 10:29 UTC, tohohosan commented
ご確認いただきありがとうございます！

2024-10-01 10:29 UTC, merged